### ISSUE TITLE
Todo: Breaking things for next release

### ISSUE THREAD

**Issue by thofma** [Nemocas/AbstractAlgebra.jl#446]
Some breaking changes that we want/need to do:
- [x] Rename some types https://github.com/Nemocas/AbstractAlgebra.jl/pull/443
- [x] `change_base_ring`, `map` order of arguments https://github.com/Nemocas/AbstractAlgebra.jl/issues/421
- [x] <s>Check consistency of function names (e.g. `mat` vs `matrix`, `poly` vs `polynomial`, `coeff` vs `coefficient`)</s>.
- [ ] Agree on #453 

<s>I added the last point, because why not.</s> Once these things are done, we will tag a new release. Then we can go on and adjust Singular and Nemo. I think most of the other open issues are bugs/features and probably non-breaking.

**Comment by rfourquet** [comment]
Close?
