### ISSUE TITLE
Issues to be closed before version 1.0

### ISSUE THREAD

**Issue by wbhart** [Nemocas/AbstractAlgebra.jl#492]
Here is a list of tickets that should be blockers for an AbstractAlgebra version 1.0:

- [x] https://github.com/Nemocas/AbstractAlgebra.jl/issues/11 isunit for polynomials over Z/nZ
- [X] https://github.com/Nemocas/AbstractAlgebra.jl/issues/13 setlength! doesn't support immutables
- [X] https://github.com/Nemocas/AbstractAlgebra.jl/issues/16 set_val!, set_length!, set_prec! don't support immutables
- [X] https://github.com/Nemocas/AbstractAlgebra.jl/issues/27 Examples of HNF needed in docs
- [X] https://github.com/Nemocas/AbstractAlgebra.jl/issues/28 Generic SNF needs docs
- [X] https://github.com/Nemocas/AbstractAlgebra.jl/issues/29 Popov form needs examples
- [X] https://github.com/Nemocas/AbstractAlgebra.jl/issues/30 popov_with_transform is documented but not tested
- [X] https://github.com/Nemocas/AbstractAlgebra.jl/issues/70 Nullspace documentation gives floating point example
- [X] https://github.com/Nemocas/AbstractAlgebra.jl/issues/155 AbstractAlgebra inv
- [X] https://github.com/Nemocas/AbstractAlgebra.jl/issues/208 Document union types such as RingElement, FieldElement
- [X] https://github.com/Nemocas/AbstractAlgebra.jl/issues/213 Doc for inv of Puiseux points to matrix inv
- [ ] https://github.com/Nemocas/AbstractAlgebra.jl/issues/214 Decent matrix tests
- [X] https://github.com/Nemocas/AbstractAlgebra.jl/issues/216 rand for NumberField interface clash
- [X] https://github.com/Nemocas/AbstractAlgebra.jl/issues/245 Runtime regression for elements of a PermGroup
- [X] https://github.com/Nemocas/AbstractAlgebra.jl/issues/247 fflu! bug for polys over a residue ring
- [X] https://github.com/Nemocas/AbstractAlgebra.jl/issues/274 @PolynomialRing macro creates wrong type of poly
- [X] https://github.com/Nemocas/AbstractAlgebra.jl/issues/315 Bug in divexact
- [X] https://github.com/Nemocas/AbstractAlgebra.jl/issues/316 Stack overflow in divexact_left/right
- [X] https://github.com/Nemocas/AbstractAlgebra.jl/issues/467 Make docstrings consistent
- [X] https://github.com/Nemocas/AbstractAlgebra.jl/issues/470 MatrixAlgebra-test.jl should not test zero_matrix/identity_matrix
- [X] https://github.com/Nemocas/AbstractAlgebra.jl/issues/472 Clarify matrix docs
- [X] https://github.com/Nemocas/AbstractAlgebra.jl/issues/485 Function to convert AbstractAlgebra matrix to Julia array
- [X] https://github.com/Nemocas/AbstractAlgebra.jl/issues/490 Fix similar, map_coeffs, map_entries, change_base_ring
- [ ] https://github.com/Nemocas/AbstractAlgebra.jl/issues/643 Improve linear system solving
- [X] https://github.com/Nemocas/AbstractAlgebra.jl/issues/508 lc vs lead naming confusion
- [X] https://github.com/Nemocas/AbstractAlgebra.jl/issues/639 Add issnf, ispopov and isweak_popov functions
- [X] https://github.com/Nemocas/AbstractAlgebra.jl/issues/640 Popov form is not tested/working

**Comment by thofma** [comment]
Why must we do a "1.0" release?

**Comment by wbhart** [comment]
We don't have to. But why not?

**Comment by thofma** [comment]
Version number "1.0" sounds so mature. I think we already did a great job, but we are still lacking basic functionality to do linear system solving. Even in the field case. Maybe this should be on the list?

**Comment by rfourquet** [comment]
Just in case you don't know about the functionality and in case you may like to use it, Github has a [milestones](https://help.github.com/en/articles/about-milestones) feature which can ease managing issues/PR related to a specific release.

**Comment by wbhart** [comment]
Thanks, I did know about it, but forgot in this case. Doesn't matter too much now.

**Comment by lgoettgens** [comment]
This is outdated and we would use a milestone nowadays (or a new list)
